// Auto-generated by scripts/generate-preload-manifest.mjs
// Do not edit by hand
export const imageFiles: string[] = [
  "/favicon.svg",
  "/images/icon-next.svg",
  "/images/icon-pause.svg",
  "/images/icon-play.svg",
  "/images/icon-prev.svg",
  "/images/icon-stop.svg",
  "/images/init-bg.svg",
  "/images/init-btn.svg",
  "/images/init-char1.png",
  "/images/init-char2.png",
  "/images/init-msg.png",
  "/images/init-ttl.svg",
  "/images/logo.svg",
  "/images/logo.webp",
  "/images/material1.svg",
  "/images/material4.png"
] as const;
export const videoFiles: string[] = [
  "/videos/init-menu2.mp4",
  "/videos/init-menu3.mp4",
  "/videos/init.mp4",
  "/videos/material2-1.mp4",
  "/videos/material2-2.mp4",
  "/videos/material3-1.mp4",
  "/videos/material3-2.mp4",
  "/videos/material4-1.mp4",
  "/videos/material5-1.mp4",
  "/videos/material5-2.mp4",
  "/videos/material5-3.mp4",
  "/videos/step1.mp4",
  "/videos/step2.mp4",
  "/videos/step3.mp4",
  "/videos/step4.mp4",
  "/videos/step5.mp4"
] as const;
