name: Tauri Release Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: tauri-apps/tauri-action@v0
        with:
          args: build
          projectPath: "."
          tagName: ${{ github.ref_name }}
          releaseName: "App ${{ github.ref_name }}"
          releaseDraft: true
          prerelease: false
