name: Release Tauri App

on:
  push:
    tags:
      - 'v*' # Triggers on pushes to tags starting with 'v'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your desired Node.js version

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.os == 'macos-latest' && 'aarch64-apple-darwin' || '' }} # Example for macOS M1 builds

      - name: Install dependencies (Rust & Node.js)
        run: |
          npm install # Or yarn install, pnpm install

      - name: Build and Release Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for creating/uploading to releases
        with:
          tagName: v__TAG__ # Will be replaced with the actual tag name by the action
          releaseName: 'Tauri App v__TAG__'
          releaseBody: 'See the changelog for details.'
          releaseDraft: true # Set to false to publish immediately
          prerelease: false # Set to true for pre-releases
