name: Tauri Release Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Node.js のセットアップ（npm コマンドに必要）
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # Rust のセットアップ（tauri-cli に必要）
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Tauri CLI をグローバルにインストール
      - run: cargo install tauri-cli

      # 依存インストール
      - run: npm install

      # Tauri ビルド（自動でバイナリとリリース作成）
      - uses: tauri-apps/tauri-action@v0
        with:
          args: build
          projectPath: "."
          tagName: ${{ github.ref_name }}
          releaseName: "App ${{ github.ref_name }}"
          releaseDraft: true
          prerelease: false
